const WEB3_LOCAL_INSTANCE = "http://localhost:7545";
const WEB3_FANTOM_INSTANCE = "wss://wsapi.fantom.network";

const FANTOM_ID = 250;

const FANTOM_NETWORK = {
  method: "wallet_addEthereumChain",
  params: [
    {
      chainId: `0x${FANTOM_ID.toString(16)}`,
      chainName: "Fantom Opera",
      nativeCurrency: {
        name: "FTM",
        symbol: "ftm",
        decimals: 18,
      },
      rpcUrls: ["https://rpc.ftm.tools"],
      blockExplorerUrls: [`https://ftmscan.com`],
    },
  ],
};

const RARITY_BASE_MAX_SCORE = 32;

const RARITY_SUMMONERS = (accountId) =>
  `https://api.ftmscan.com/api?module=account&action=tokennfttx&contractaddress=0xce761D788DF608BD21bdd59d6f4B54b2e27F25Bb&address=${accountId}&apikey=81CTWCS4N63GKQ4FUZ2YMC85M98YGUNTCN`;

const CODEX__ABI_SKILLS = [
  {
    inputs: [],
    name: "appraise",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "balance",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "bluff",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "class",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "climb",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "concentration",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "craft",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "decipher_script",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "diplomacy",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "disable_device",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "disguise",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "escape_artist",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "forgery",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "gather_information",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "get_attribute",
    outputs: [{ internalType: "string", name: "attribute", type: "string" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "handle_animal",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "heal",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "hide",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "index",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "intimidate",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "jump",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "knowledge",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "listen",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "move_silently",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "open_lock",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "perform",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "profession",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "ride",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "search",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "sense_motive",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
    name: "skill_by_id",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "sleight_of_hand",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "speak_language",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "spellcraft",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "spot",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "survival",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "swim",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "tumble",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "use_magic_device",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "use_rope",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "uint256", name: "attribute_id", type: "uint256" },
      { internalType: "uint256", name: "synergy", type: "uint256" },
      { internalType: "bool", name: "retry", type: "bool" },
      { internalType: "bool", name: "armor_check_penalty", type: "bool" },
      { internalType: "string", name: "check", type: "string" },
      { internalType: "string", name: "action", type: "string" },
    ],
    stateMutability: "pure",
    type: "function",
  },
];
const CODEX_ADDRESS_SKILLS = "0x67ae39a2Ee91D7258a86CD901B17527e19E493B3";

const RARITY_ABI_SKILLS = [
  {
    inputs: [{ internalType: "uint256", name: "_class", type: "uint256" }],
    name: "base_per_class",
    outputs: [{ internalType: "uint256", name: "base", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_class", type: "uint256" },
      { internalType: "uint8[36]", name: "_skills", type: "uint8[36]" },
    ],
    name: "calculate_points_for_set",
    outputs: [{ internalType: "uint256", name: "points", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_class", type: "uint256" }],
    name: "class_skills",
    outputs: [{ internalType: "bool[36]", name: "_skills", type: "bool[36]" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_class", type: "uint256" }],
    name: "class_skills_by_name",
    outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_summoner", type: "uint256" }],
    name: "get_skills",
    outputs: [{ internalType: "uint8[36]", name: "", type: "uint8[36]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_summoner", type: "uint256" },
      { internalType: "uint8[36]", name: "_skills", type: "uint8[36]" },
    ],
    name: "is_valid_set",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_attribute", type: "uint256" }],
    name: "modifier_for_attribute",
    outputs: [{ internalType: "int256", name: "_modifier", type: "int256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_summoner", type: "uint256" },
      { internalType: "uint8[36]", name: "_skills", type: "uint8[36]" },
    ],
    name: "set_skills",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "skills",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "int256", name: "_int", type: "int256" },
      { internalType: "uint256", name: "_class", type: "uint256" },
      { internalType: "uint256", name: "_level", type: "uint256" },
    ],
    name: "skills_per_level",
    outputs: [{ internalType: "uint256", name: "points", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
];
const RARITY_ADDRESS_SKILLS = "0x51C0B29A1d84611373BA301706c6B4b72283C80F";

const RARITY_ABI = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "approved",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      { indexed: false, internalType: "bool", name: "approved", type: "bool" },
    ],
    name: "ApprovalForAll",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "level",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "summoner",
        type: "uint256",
      },
    ],
    name: "leveled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "class",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "summoner",
        type: "uint256",
      },
    ],
    name: "summoned",
    type: "event",
  },
  {
    inputs: [{ internalType: "uint256", name: "_summoner", type: "uint256" }],
    name: "adventure",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "adventurers_log",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "approve",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "class",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "classes",
    outputs: [{ internalType: "string", name: "description", type: "string" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "getApproved",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "operator", type: "address" },
    ],
    name: "isApprovedForAll",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "level",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_summoner", type: "uint256" }],
    name: "level_up",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "next_summoner",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "ownerOf",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      { internalType: "bytes", name: "_data", type: "bytes" },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "operator", type: "address" },
      { internalType: "bool", name: "approved", type: "bool" },
    ],
    name: "setApprovalForAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_summoner", type: "uint256" },
      { internalType: "uint256", name: "_xp", type: "uint256" },
    ],
    name: "spend_xp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_class", type: "uint256" }],
    name: "summon",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_summoner", type: "uint256" }],
    name: "summoner",
    outputs: [
      { internalType: "uint256", name: "_xp", type: "uint256" },
      { internalType: "uint256", name: "_log", type: "uint256" },
      { internalType: "uint256", name: "_class", type: "uint256" },
      { internalType: "uint256", name: "_level", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_summoner", type: "uint256" }],
    name: "tokenURI",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "xp",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "curent_level", type: "uint256" },
    ],
    name: "xp_required",
    outputs: [
      { internalType: "uint256", name: "xp_to_next_level", type: "uint256" },
    ],
    stateMutability: "pure",
    type: "function",
  },
];
const RARITY_ADDRESS = "0xce761d788df608bd21bdd59d6f4b54b2e27f25bb";

const RARITY_ABI_ATTRIBUTES = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "summoner",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "strength",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "dexterity",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "constitution",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "intelligence",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "wisdom",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "charisma",
        type: "uint32",
      },
    ],
    name: "Created",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "leveler",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "summoner",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "strength",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "dexterity",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "constitution",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "intelligence",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "wisdom",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "charisma",
        type: "uint32",
      },
    ],
    name: "Leveled",
    type: "event",
  },
  {
    inputs: [
      { internalType: "uint256", name: "current_level", type: "uint256" },
    ],
    name: "abilities_by_level",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "ability_scores",
    outputs: [
      { internalType: "uint32", name: "strength", type: "uint32" },
      { internalType: "uint32", name: "dexterity", type: "uint32" },
      { internalType: "uint32", name: "constitution", type: "uint32" },
      { internalType: "uint32", name: "intelligence", type: "uint32" },
      { internalType: "uint32", name: "wisdom", type: "uint32" },
      { internalType: "uint32", name: "charisma", type: "uint32" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "score", type: "uint256" }],
    name: "calc",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_str", type: "uint256" },
      { internalType: "uint256", name: "_dex", type: "uint256" },
      { internalType: "uint256", name: "_const", type: "uint256" },
      { internalType: "uint256", name: "_int", type: "uint256" },
      { internalType: "uint256", name: "_wis", type: "uint256" },
      { internalType: "uint256", name: "_cha", type: "uint256" },
    ],
    name: "calculate_point_buy",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "character_created",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_summoner", type: "uint256" }],
    name: "increase_charisma",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_summoner", type: "uint256" }],
    name: "increase_constitution",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_summoner", type: "uint256" }],
    name: "increase_dexterity",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_summoner", type: "uint256" }],
    name: "increase_intelligence",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_summoner", type: "uint256" }],
    name: "increase_strength",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_summoner", type: "uint256" }],
    name: "increase_wisdom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "level_points_spent",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_summoner", type: "uint256" },
      { internalType: "uint32", name: "_str", type: "uint32" },
      { internalType: "uint32", name: "_dex", type: "uint32" },
      { internalType: "uint32", name: "_const", type: "uint32" },
      { internalType: "uint32", name: "_int", type: "uint32" },
      { internalType: "uint32", name: "_wis", type: "uint32" },
      { internalType: "uint32", name: "_cha", type: "uint32" },
    ],
    name: "point_buy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_summoner", type: "uint256" }],
    name: "tokenURI",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
];
const RARITY_ADDRESS_ATTRIBUTES = "0xb5f5af1087a8da62a23b08c00c6ec9af21f397a1";

const RARITY_ABI_NAMES = [
  {
    inputs: [],
    name: "cost",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_summoner", type: "uint256" }],
    name: "full_name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "n",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_summoner", type: "uint256" },
      { internalType: "string", name: "_name", type: "string" },
    ],
    name: "set_name",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_summoner", type: "uint256" }],
    name: "summoner_name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_lvl", type: "uint256" }],
    name: "title",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "pure",
    type: "function",
  },
];
const RARITY_ADDRESS_NAMES = "0x4c40ce3fb33a6781c903bc830804de4195cc966f";
const RARITY_ABI_DUNGEONS = [
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "from", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "to", type: "uint256" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "from", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "to", type: "uint256" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    inputs: [{ internalType: "uint256", name: "_summoner", type: "uint256" }],
    name: "adventure",
    outputs: [{ internalType: "uint256", name: "reward", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "adventurers_log",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "allowance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "from", type: "uint256" },
      { internalType: "uint256", name: "spender", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_dex", type: "uint256" }],
    name: "armor_class",
    outputs: [{ internalType: "int256", name: "", type: "int256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_class", type: "uint256" },
      { internalType: "uint256", name: "_str", type: "uint256" },
      { internalType: "uint256", name: "_level", type: "uint256" },
    ],
    name: "attack_bonus",
    outputs: [{ internalType: "int256", name: "", type: "int256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_class", type: "uint256" }],
    name: "base_attack_bonus_by_class",
    outputs: [{ internalType: "uint256", name: "attack", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_class", type: "uint256" },
      { internalType: "uint256", name: "_level", type: "uint256" },
    ],
    name: "base_attack_bonus_by_class_and_level",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_str", type: "uint256" }],
    name: "damage",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "dungeon_armor_class",
    outputs: [{ internalType: "int256", name: "", type: "int256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "dungeon_damage",
    outputs: [{ internalType: "int256", name: "", type: "int256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "dungeon_health",
    outputs: [{ internalType: "int256", name: "", type: "int256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "dungeon_to_hit",
    outputs: [{ internalType: "int256", name: "", type: "int256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_class", type: "uint256" }],
    name: "health_by_class",
    outputs: [{ internalType: "uint256", name: "health", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_class", type: "uint256" },
      { internalType: "uint256", name: "_level", type: "uint256" },
      { internalType: "uint32", name: "_const", type: "uint32" },
    ],
    name: "health_by_class_and_level",
    outputs: [{ internalType: "uint256", name: "health", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_attribute", type: "uint256" }],
    name: "modifier_for_attribute",
    outputs: [{ internalType: "int256", name: "_modifier", type: "int256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_summoner", type: "uint256" }],
    name: "scout",
    outputs: [{ internalType: "uint256", name: "reward", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "int256", name: "_attack_bonus", type: "int256" }],
    name: "to_hit_ac",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "from", type: "uint256" },
      { internalType: "uint256", name: "to", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "transfer",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "executor", type: "uint256" },
      { internalType: "uint256", name: "from", type: "uint256" },
      { internalType: "uint256", name: "to", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const RARITY_ABI_GOLD = [
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "from", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "to", type: "uint256" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "from", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "to", type: "uint256" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "allowance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "from", type: "uint256" },
      { internalType: "uint256", name: "spender", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "summoner", type: "uint256" }],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "summoner", type: "uint256" }],
    name: "claimable",
    outputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "claimed",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "from", type: "uint256" },
      { internalType: "uint256", name: "to", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "transfer",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "executor", type: "uint256" },
      { internalType: "uint256", name: "from", type: "uint256" },
      { internalType: "uint256", name: "to", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "level", type: "uint256" }],
    name: "wealth_by_level",
    outputs: [{ internalType: "uint256", name: "wealth", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
];
const RARITY_ADDRESS_GOLD = "0x2069B76Afe6b734Fb65D1d099E7ec64ee9CC76B2";
const RARITY_ADDRESS_DUNGEONS = "0x2A0F1cB17680161cF255348dDFDeE94ea8Ca196A";

const RARITY_ABI_FOREST = [
  {
    inputs: [{ internalType: "address", name: "_rarityAddr", type: "address" }],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "approved",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      { indexed: false, internalType: "bool", name: "approved", type: "bool" },
    ],
    name: "ApprovalForAll",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "summonerId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "ResearchStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "treasureId",
        type: "uint256",
      },
    ],
    name: "TreasureDiscovered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "treasureId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "summonerId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newLevel",
        type: "uint256",
      },
    ],
    name: "TreasureLevelUp",
    type: "event",
  },
  {
    inputs: [],
    name: "_tokenIdCounter",
    outputs: [{ internalType: "uint256", name: "_value", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "approve",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "summonerId", type: "uint256" }],
    name: "discover",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "getApproved",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "operator", type: "address" },
    ],
    name: "isApprovedForAll",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "summonerId", type: "uint256" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "levelUp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "ownerOf",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "rarityContract",
    outputs: [{ internalType: "contract IRarity", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      { internalType: "bytes", name: "_data", type: "bytes" },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "operator", type: "address" },
      { internalType: "bool", name: "approved", type: "bool" },
    ],
    name: "setApprovalForAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "summonerId", type: "uint256" },
      { internalType: "uint256", name: "timeInDays", type: "uint256" },
    ],
    name: "startResearch",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "tokenURI",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "treasure",
    outputs: [
      { internalType: "string", name: "_itemName", type: "string" },
      { internalType: "uint256", name: "_magic", type: "uint256" },
      { internalType: "uint256", name: "_level", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "currentLevel", type: "uint256" },
    ],
    name: "xpRequired",
    outputs: [
      { internalType: "uint256", name: "xpToNextLevel", type: "uint256" },
    ],
    stateMutability: "pure",
    type: "function",
  },
];
const RARITY_ADDRESS_FOREST = "0xb37d3d79ea86B0334d9322c695339D577A3D57be";

export {
  RARITY_ABI,
  RARITY_ADDRESS,
  RARITY_ABI_ATTRIBUTES,
  RARITY_ADDRESS_ATTRIBUTES,
  RARITY_ADDRESS_NAMES,
  RARITY_ABI_FOREST,
  RARITY_ADDRESS_FOREST,
  RARITY_ABI_NAMES,
  CODEX__ABI_SKILLS,
  CODEX_ADDRESS_SKILLS,
  RARITY_ADDRESS_SKILLS,
  RARITY_ABI_SKILLS,
  RARITY_ABI_DUNGEONS,
  RARITY_ADDRESS_GOLD,
  RARITY_ABI_GOLD,
  RARITY_ADDRESS_DUNGEONS,
  WEB3_FANTOM_INSTANCE,
  WEB3_LOCAL_INSTANCE,
  FANTOM_NETWORK,
  FANTOM_ID,
  RARITY_SUMMONERS,
  RARITY_BASE_MAX_SCORE,
};
